function [projinds,rotinds,SSDs,transinds,scales] = ...
    distribute_SSDs_fbm(projnorms,projcoeffs,imcoeffs,ips,ctfinds,numim,numctf,numproj,numrot,searchtrans,imnorms,maxmem,...
    ipaddrs,login,ppath,remmat,varmat,sleeptime,resfold,printout)

[ncluster ~] = find(ipaddrs==' ');
ncluster = size(ncluster,2)+1;
